### PR TITLE
Use dot notation instead array of paths.

### PR DESCRIPTION
**Pull request by eloyucu**

### CODE REVIEW

**Comment by tamerh** [comment]
Hi @eloyucu :), this approach obviously better and maybe extended more later. Here is my initial minor comments,

- getIndex better again with receiver and maybe name pathIndex? 
- For readme better to keep simple based on existing book example. Maybe just few lines of use cases with book attribute and childs? no need explanation there :)  We can move your existing doc to the func doc?

**Comment by eloyucu** [comment]
Done ;)

PS: I am not sure about if you will like the Readme, check it and notice me if you see something you don´t like.

**Comment by tamerh** [comment]
Cool. Let me do the README part if you revert or use the book attributes because tag1.tag12@att0 is only for test cases. In few days i will tag this as a new version.

**Comment by eloyucu** [comment]
ahhh!! I didn´t understand the "existing book exampe". Ok!!! One second... I am doing the GetNode and GetNodes functions.

**Comment by tamerh** [comment]
no worries yeah in readme there is separate book example. 

Actually yes i was also thinking somehow getting also childs in a efficient way with your path approach.

**Comment by eloyucu** [comment]
I think now it is done!! :)

Note: I didn´t do explicit testing for the new functions `GetNode` and `GetNodes` because they are implicit tested in `GetValue`, I change the body of this function to use `GetNode`, which uses `GetNodes`.

**Comment by eloyucu** [comment]
ummmm Should be better hide the `Childs`, `InnerText` and `Attrs` fields to the outside of the XMLElement??  I mean, make them private and access to them only through the `GetNodes`, `GetNode` and `GetValue` functions. 

Makes it sense??

**Comment by tamerh** [comment]
GetNode and GetNodes looks very cool...but with these childs still needed because 

`xml.GetNodes("tag1.tag11")
`
this assume always the first `tag1` right? Need to leave now i will think about.

**Comment by tamerh** [comment]
Hi again @eloyucu :)

I thought again this and i think it is better either give full xpath support or just keep library 
as it is for now and leave users to write these functions based on their needs. For xpath there are existing implementations in go or python one can be taken example and integrated to this parser.

But in a way to separate the xpath part and existing functionality part if this affecting the performance. Xpath can be activated by user, parser can work according to this if needed. Reason is, I think xpath is more suitable for usecase like querying the parsed element or more clean way to access parsed elements childs for small or medium files. But as my usecase i am only interested to parse large files as fast and efficient as possible. I have some files with size more than 600GB. For example i am accessing the element like the example in the previous comment which require multi level childs. Probably implementing it with xpath will require merging slices and will bring overhead in theory. That's why If this is the case i would prefer the separate xpath and existing functionality.

Full xpath support takes time, I would work on implementation but at the moment i am busy with another project. But feel free to implement if you are interested either here in separate branch or go with the fork.

**Comment by eloyucu** [comment]
Ummm I am not sure what you mean when you talk about the issues of the multi level childs... with this new approach you can access to different levels of the childrens using the "brackets notation": `father[2].son.grandson[6]` if the index is missing the code will return position [0]. This functionality allowes to do things like:

```
for i, _ := range whateverSlice {
    n := xml.GetNode(fmt.Sprintf("father[2].son.grandson[%d]", i))
}
```
But... anyway, I am 100% agree with you when you say that people is using this library accessing through Childs, InnerText, and Attrs... so it is better to keep this functionality.

**Comment by tamerh** [comment]
Ok say, i want all the `grandsons` for all `fathers` this needs another for loop right?

**Comment by eloyucu** [comment]
Yes, you are right... you´d need to loop doing something like:
```
for _, f := xml.GetNodes("father"){
    for _, s := f.GetNodes("son"){
          for _, gs := s.GetNodes("grandsons"){
```
in case that `fathers` have more than one `son`, if there is only one `son` per `father`:
```
for _, f := xml.GetNodes("father"){
          for _, gs := s.GetNodes("son.grandsons"){
```

**Comment by tamerh** [comment]
yes this is my point, extra loops would be another variation of `Childs` which could be confusing.

But with xpath support, this query is doable and user can choose either direct access with existing functions or use xpath query depends on usecase.

**Comment by eloyucu** [comment]
ok!! But... as it is... you like, isn´t?? I mean, if you like it and you could accept the PR would be great, because in this way I don´t need to change this dependecy to my fork... only update the references :)

Thanks.

**Comment by tamerh** [comment]
Sure i like! this PR show your xpath way usage would be very useful. After thinking I just want to add full xpath support otherwise could be confusing for me and people also could ask why this work and not this.

So for now lets not add this and keep your fork and i don't think main parser will change and require you a extra work. When xpath implemented you could just switch to this one again.

**Comment by eloyucu** [comment]
Hi, I added the function `GetAllNodes` which allows to get all nodes from a xpath, passing through all the branches of the xml structure and getting all the leafs. So now we won´t need to do this: https://github.com/tamerh/xml-stream-parser/pull/7#issuecomment-517189339

Is there any other function you think could be great to add??

**Comment by tamerh** [comment]
Hi again @eloyucu  thanks for looking this again. Trust me i will review this again with also the xpath implemented libraries when i have some time. 

I made commit for an new issue #8 and made commit in master and reverted your previous PR since a variation of this PR will be merged. So merge with your fork it shouldn't give a conflict since it is not related the area you have changed.

**Comment by eloyucu** [comment]
Hi... I added new functions like `GetValueDeep`, maybe you can take a look.

Thanks ;)

**Comment by tamerh** [comment]
Hi :)...ok thanks..soon i will start working on xpath implementation(probably integrating one of existing implementations) with reviewing again this PR commits. I will let you know.

**Comment by tamerh** [comment]
Hi @eloyucu, I have committed first xpath implementation to master. I tried to separate from existing logic and used a external library which allow rich set of query functionalities hopefully also address your cases. Please give it a try.

Tamer

**Pull request closed without merging**
