### PR TITLE
Add a function to get the value of a field by path and indexation.

### PR DESCRIPTION
**Pull request by eloyucu**
Add a function to get the value of a field by path and indexation.

### CODE REVIEW

**Comment by tamerh** [comment]
Hi Eloy,

This is cool thanks for adding. First impressions,

Why no function receiver, maybe receiver of XMLElement and remove the first parameter from function?

and instead GetField name how about GetValue isn't it more informative?

Tamer

**Comment by eloyucu** [comment]
Hi @tamerh here you have ;)

**Comment by tamerh** [comment]
Great. Just better with pointer receiver?  And i guess both "else" are not needed as golint gives me warning?

**Comment by eloyucu** [comment]
ok!! Done :)

**Comment by tamerh** [comment]
Merged:)

**Pull request merged**
