### PR TITLE
Add readBytes variant which uses Reader.ReadBytes to find character

### PR DESCRIPTION
**Pull request by imirkin**
In several cases, we try to find the next character (e.g. "<") and don't
really care about what comes until then. The existing ReadBytes method
does exactly this, using the reader's buffered data, which means it can
go much faster.

While we're at it, also speed up whitespace checking.

This results in a ~10% speed improvement on a sample data set.

Several other places in the library could be optimized, but they were
not important in my case and present some additional complexity.

NOTE: This has only gotten limited testing. Please run through any local tests you may have to ensure I didn't screw something up.

### CODE REVIEW

**Comment by tamerh** [comment]
Thanks. This sounds sense without additional complexity. I will check and test next week.

**Comment by imirkin** [comment]
@tamerh bumping in case this fell by the wayside, as I know side projects often can.

**Comment by tamerh** [comment]
Yes @imirkin I am a bit busy with another project. I reviewed it and looks OK to me and makes code cleaner but want to check with you the benchmarks

```
Benchmark1-2   	   10000	    103895 ns/op	   19848 B/op	     185 allocs/op
Benchmark2-2   	   10000	    102035 ns/op	   20280 B/op	     186 allocs/op
Benchmark3-2   	   10604	    135596 ns/op	   21624 B/op	     258 allocs/op
--------------------------------------------------------------------------------------------------------------
Benchmark1-2   	   10000	    106607 ns/op	   19480 B/op	     151 allocs/op
Benchmark2-2   	   10000	    104794 ns/op	   19992 B/op	     158 allocs/op
Benchmark3-2   	    9925	    112542 ns/op	   21336 B/op	     230 allocs/op

```

First ones with your changes  and the second are current master. These are simple benchmarks but still gives an idea `Benchmark3` case clearly faster but that one is with `xpath` feature enabled. I would see impacts more in `Benchmark1` and `Benchmark2` and in those cases looks slightly faster but making more allocations. At the moment I have very poor Ubuntu machine wondering your results? And did you use `xpath` feature in your comparison?

**Comment by imirkin** [comment]
I did not have xpath enabled -- it actually looks much worse with the third test case, no? That's quite odd. My test file was a ~600MB xml file that I was just processing with "time" (it takes like 10s to process, so changes are fairly visible), running on a fairly ancient i7-920 CPU. Unfortunately I can't share the test file as the contents are private.

The actual improvements would be highly dependent on the contents of the file itself. For example a file with no spaces or short tags would have less improvement than one where a lot of stuff has to be skipped.

More allocations makes some sense - I think ReadBytes will end up allocating arrays while ReadByte won't.

I'll try to come up with some representative samples to benchmark, and also try it on a more modern i7-6700 CPU.

**Comment by tamerh** [comment]
I rerun few times the `Benchmark3` actually result difference are similar with first 2 benchmarks. you can ignore above benchmark result probably this happened due to my unstable machine. 

yes would be good to see your representative benchmarks if possible with avarege memory usage comparisons based on your file.

**Comment by imirkin** [comment]
I noticed an odd effect when playing with benchmarks -- setting it to use a single CPU *drastically* improves performance. Not sure if it's just because the benchmarks are so small and the channel overhead is relatively high? Or something else?

Working on a larger benchmark...

**Comment by tamerh** [comment]
Yes channels have overheads. I can't remember exactly the difference  but from my early impl tests remembering around 20 percent. But channels are useful for multi CPU and stream processing. 
Ok will be good to see  your benchmarks.

**Comment by imirkin** [comment]
It was more like 20x faster...

```
 $ go test -run=Bench -bench=. -cpu 1
goos: linux
goarch: amd64
pkg: github.com/tamerh/xml-stream-parser
Benchmark1        413350              2624 ns/op
Benchmark2        455991              2552 ns/op
Benchmark3        457154              2553 ns/op
PASS

$ go test -run=Bench -bench=. -cpu 2
goos: linux
goarch: amd64
pkg: github.com/tamerh/xml-stream-parser
Benchmark1-2       40024             29489 ns/op
Benchmark2-2       39615             30124 ns/op
Benchmark3-2       35036             34093 ns/op
PASS
```

(This includes my changes, but without my changes it's a similar difference.) Also with multiple CPUs, sometimes I see a doubling of times randomly in the benchmarks.

**Comment by tamerh** [comment]
This seems to be related with different number of iterations in the first column. Try adding the `-benchtime=1000x`

**Comment by imirkin** [comment]
With 1000x, the times do seem similar. But if you bump it up to
100000x, I get similar results again:

```
$ go test -run=Bench -bench=. -benchtime=100000x -cpu 1
goos: linux
goarch: amd64
pkg: github.com/tamerh/xml-stream-parser
Benchmark1        100000              3684 ns/op
Benchmark2        100000              2890 ns/op
Benchmark3        100000              2966 ns/op
PASS
$ go test -run=Bench -bench=. -benchtime=100000x -cpu 2
goos: linux
goarch: amd64
pkg: github.com/tamerh/xml-stream-parser
Benchmark1-2      100000             31673 ns/op
Benchmark2-2      100000             30875 ns/op
Benchmark3-2      100000             35003 ns/op
PASS
```

**Comment by tamerh** [comment]
you are right, I profiled the benchmark using the `-cpuprofile cpu.out` bench param. And then I used `go tool pprof -http=:8080 cpu.out` to visualize. So it seems to me file reading becoming bottleneck for multi CPU. I don't know the exact reason but probably opening too many files with multi CPU hit some OS limits. I confirmed this by using string input instead of file and results are as expected even for the 1 million iteration.

I also made tests with large file(2.6 GB) using `runtime.GOMAXPROCS(1)` I haven't seen any affect and seems slower as expected.  But this wasn't benchmark just regular parsing and obviously not too many files are opened like in the benchmark.

So I think for those benchmark keeping the `-benchtime` small would be better right?

**Comment by tamerh** [comment]
@imirkin any update on this issue?

**Comment by imirkin** [comment]
Nope, haven't had time to create a proper benchmark.

**Pull request closed without merging**
