### PR TITLE
Add readBytes variant which uses Reader.ReadBytes to find character

### PR DESCRIPTION
**Pull request by imirkin**
In several cases, we try to find the next character (e.g. "<") and don't
really care about what comes until then. The existing ReadBytes method
does exactly this, using the reader's buffered data, which means it can
go much faster.

While we're at it, also speed up whitespace checking.

This results in a ~10% speed improvement on a sample data set.

Several other places in the library could be optimized, but they were
not important in my case and present some additional complexity.

NOTE - This is the same as in PR #16, but with a benchmark included.

### CODE REVIEW

**Comment by tamerh** [comment]
I would avoid new `sample2.xml` which doesn't look proper existing `sample.xml` file can be used by increasing its size. With current test benchmarks(master) I haven't seen the speed changes which can be normal but seen more memory allocation as discussed before. 

I created new repo [here](https://github.com/tamerh/xmlbench) for benchmark via xml file from my use-case and I saw ~6% speed improvments. But in addition to memory tradeoff I also observed slightly more power usage. Overall still it may be OK to merge but It would be better investigate more to have this feature with lesser tradeoff if possible.

**Comment by imirkin** [comment]
With the "sample2" file, I saw ~10% improvements as well. You did not?

The sample2 file is specially crafted to reflect the types of situations where skipping bytes more efficiently matters.

I'll have a look at your sample + benchmark program tonight.

**Comment by tamerh** [comment]
I saw your improvment with sample2.xml. Just there is no need to keep another sample file. Improvment can be also seen with existing file by increasing the size a bit. Ok let me know.

**Comment by imirkin** [comment]
So with your original xmlbench, I get a 3.5% improvement:

```
starting prod
2020/12/17 23:47:24 Process id  15243
2020/12/17 23:53:47 finished took 6m22.74677735s
killing top process
starting development version
2020/12/17 23:53:48 Process id  15467
2020/12/17 23:59:58 finished took 6m9.551343078s
killing top process
```

However when I change it to create the parser with a bunch of skips like this:

`NewXMLParser(br, "entry").SkipElements([]string{"organism", "organismHost", "comment", "dbReference", "proteinExistence", "feature", "evidence", "sequence"})`

then the results are much stronger in favor my variant -- about 8.5%:

```
starting prod
2020/12/18 00:02:28 Process id  16396
2020/12/18 00:06:48 finished took 4m19.763946312s
killing top process
starting development version
2020/12/18 00:06:48 Process id  16623
2020/12/18 00:10:46 finished took 3m57.901044038s
killing top process
```

Your version of top must be different, I don't have a -stats option. Mine is from procps-ng.

Doing stuff in bulk will always end up using more memory than not... but it should be a fairly fixed amount of memory, not a function of the input. Given that you agree it's faster, not sure why you're worried about it.

**Comment by imirkin** [comment]
One thing we could do is use ReadSlice instead of ReadBytes. We'd have to handle buffer-full errors directly, and also take extra care to make copies of the buffer data for e.g. .string() where we can't have the underlying storage get messed up. Not sure it'd be any better TBH.

**Comment by tamerh** [comment]
A bit late anwser but I am reluctant to switch to the `readBytes`. [It](https://github.com/golang/go/blob/249da7ec020e194208c02c8eb6a04d017bf29fea/src/bufio/bufio.go#L465) is creating internally slice.  
Also as I mentioned time is not only criteria for the performance. Memory and power usage is also important and it can affect different usecases and timing gain 3.5% is not very high . That's why I would keep as it is which is simply reading byte by byte. Happy to hear other suggestions for the improvment.

**Comment by imirkin** [comment]
OK. I thought this library was for maximizing processing speed. My bad.

**Comment by tamerh** [comment]
maximizing speed && minimizing resource

**Pull request closed without merging**
